<?php

/**
 * This file is part of the Qunity package.
 *
 * Copyright (c) Rodion Kachkin <kyleRQWS@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/** @var StdClass $config */
/** @var StdClass $data */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Welcome Qunity</title>
    <link rel="stylesheet" href="<?= $config->style ?>">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
            crossorigin="anonymous"></script>
    <script src="<?= $config->script ?>"></script>
</head>
<body>
<div class="wrapper">
    <div class="welcome">
        <div class="title">&nbsp;&nbsp;&nbsp;Q&nbsp;U&nbsp;N&nbsp;I&nbsp;T&nbsp;Y&nbsp;&nbsp;&nbsp;</div>
        <div class="info">
            <div><?= $data->version ?? '' ?></div>
            <div><?= $data->authors ?? '' ?></div>
        </div>
    </div>
</body>
</html>
